name: release

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          toolchain=$(cat go.mod | grep toolchain | cut -d ' ' -f 2 | sed 's/go*//')
          echo "GOTOOLCHAIN=go${toolchain}" >> $GITHUB_ENV
          echo "GOVERSION=${toolchain}" >> $GITHUB_ENV
          echo "GOROOT=/opt/hostedtoolcache/go/${toolchain}/x64" >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GOVERSION }}"
      - name: set environment
        uses: HatsuneMiku3939/direnv-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: release version
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: release publish
        run: |
          sudo rm -rf dist
          make release
        env:
          GORELEASER_RELEASE: true
          GORELEASER_MOUNT_CONFIG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
